### PR TITLE
Add ruby implementations to resolvedomains

### PR DESCRIPTION
**Pull request by ruevaughn**
I redid your script in ruby because that is what my Automation Framework is written in, and so I just thought i'd see if you were interested in adding it. If you are wanting to stick to python or whatever, that's fine no worries at all. The Ruby version also adds an optional -h and -v or --verbose, where instead of just the ip it outputs the corresponding hostname as well

### CODE REVIEW

**Comment by maurosoria** [comment]
This is cool! Thanks for your contribution!

**Comment by maurosoria** [comment]
I generated a new Readme with ChatGPT. Can you fix your details? I want to write your contribution!

**Comment by ruevaughn** [comment]
Sure thing, do you mind explaining which details i'm fixing? 😇

**Comment by maurosoria** [comment]
Hello again!

I updated the Readme.md and gave you reference with a link to your GitHub profile. It's my little way of saying a big thanks for the awesome work you've done!

I really believe in giving props where they're due, and I think that by giving recognition I encourage other people to participate.

Could you take a quick look and see if everything's cool? Feel free to let me know if there's something off or any other feedback.

Thanks again for your contribution!

**Pull request merged**
